param([Parameter(Mandatory=$true)][string]$RepoRoot)
Set-StrictMode -Version Latest
$ErrorActionPreference="Stop"

function Die([string]$m){ throw $m }
function EnsureDir([string]$p){ if([string]::IsNullOrWhiteSpace($p)){ Die "EnsureDir: empty path" }; if(-not (Test-Path -LiteralPath $p -PathType Container)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function WriteUtf8NoBomLf([string]$Path,[string]$Text){ $enc=New-Object System.Text.UTF8Encoding($false); $lf=($Text -replace "`r`n","`n") -replace "`r","`n"; if(-not $lf.EndsWith("`n")){ $lf += "`n" }; EnsureDir (Split-Path -Parent $Path); [System.IO.File]::WriteAllText($Path,$lf,$enc) }
function ParseGateFile([string]$Path){ if(-not (Test-Path -LiteralPath $Path -PathType Leaf)){ Die ("PARSE_GATE_MISSING: " + $Path) }; $t=$null; $e=$null; [void][System.Management.Automation.Language.Parser]::ParseFile($Path,[ref]$t,[ref]$e); if($e -and $e.Count -gt 0){ $x=$e[0]; Die ("PARSE_GATE_FAIL: {0}:{1}:{2}: {3}" -f $Path,$x.Extent.StartLineNumber,$x.Extent.StartColumnNumber,$x.Message) } }

$ScriptsDir = Join-Path $RepoRoot "scripts"
$Scratch = Join-Path $ScriptsDir "_scratch"
EnsureDir $ScriptsDir; EnsureDir $Scratch

$libPath = Join-Path $ScriptsDir "_lib_packet_constitution_v1.ps1"
$L = New-Object System.Collections.Generic.List[string]
[void]$L.Add("Set-StrictMode -Version Latest")
[void]$L.Add("$ErrorActionPreference = ""Stop""")
[void]$L.Add("")
[void]$L.Add("function PC-Die([string]$m){ throw $m }")
[void]$L.Add("function PC-EnsureDir([string]$p){ if([string]::IsNullOrWhiteSpace($p)){ PC-Die ""PC-EnsureDir: empty path"" }; if(-not (Test-Path -LiteralPath $p -PathType Container)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }")
[void]$L.Add("function PC-WriteUtf8NoBomLf([string]$Path,[string]$Text){ $enc=New-Object System.Text.UTF8Encoding($false); $lf=($Text -replace ""`r`n"",""`n"") -replace ""`r"",""`n""; if(-not $lf.EndsWith(""`n"")){ $lf += ""`n"" }; PC-EnsureDir (Split-Path -Parent $Path); [System.IO.File]::WriteAllText($Path,$lf,$enc) }")
[void]$L.Add("function PC-Sha256HexBytes([byte[]]$Bytes){ if($null -eq $Bytes){ $Bytes = @() }; $sha=[System.Security.Cryptography.SHA256]::Create(); try{ $h=$sha.ComputeHash([byte[]]$Bytes) } finally{ $sha.Dispose() }; $sb=New-Object System.Text.StringBuilder; foreach($b in $h){ [void]$sb.Append($b.ToString(""x2"")) }; return $sb.ToString() }")
[void]$L.Add("function PC-Sha256HexFile([string]$Path){ if(-not (Test-Path -LiteralPath $Path -PathType Leaf)){ PC-Die (""MISSING_FILE: "" + $Path) }; $sha=[System.Security.Cryptography.SHA256]::Create(); try{ $fs=[System.IO.File]::OpenRead($Path); try{ $h=$sha.ComputeHash($fs) } finally{ $fs.Dispose() } } finally{ $sha.Dispose() }; $sb=New-Object System.Text.StringBuilder; foreach($b in $h){ [void]$sb.Append($b.ToString(""x2"")) }; return $sb.ToString() }")
[void]$L.Add("function PC-NowUtc(){ (Get-Date).ToUniversalTime().ToString(""yyyy-MM-ddTHH:mm:ss.fffZ"") }")
[void]$L.Add("")
[void]$L.Add("function PC-EscapeJsonString([string]$s){")
[void]$L.Add("  if($null -eq $s){ return """" }")
[void]$L.Add("  $sb = New-Object System.Text.StringBuilder")
[void]$L.Add("  for($i=0;$i -lt $s.Length;$i++){")
[void]$L.Add("    $code = [int][char]$s[$i]")
[void]$L.Add("    switch($code){")
[void]$L.Add("      8  { [void]$sb.Append([char]92); [void]$sb.Append('b'); continue }")
[void]$L.Add("      9  { [void]$sb.Append([char]92); [void]$sb.Append('t'); continue }")
[void]$L.Add("      10 { [void]$sb.Append([char]92); [void]$sb.Append('n'); continue }")
[void]$L.Add("      12 { [void]$sb.Append([char]92); [void]$sb.Append('f'); continue }")
[void]$L.Add("      13 { [void]$sb.Append([char]92); [void]$sb.Append('r'); continue }")
[void]$L.Add("      34 { [void]$sb.Append([char]92); [void]$sb.Append([char]34); continue }")
[void]$L.Add("      92 { [void]$sb.Append([char]92); [void]$sb.Append([char]92); continue }")
[void]$L.Add("      default {")
[void]$L.Add("        if($code -lt 32){")
[void]$L.Add("          [void]$sb.Append([char]92); [void]$sb.Append('u')")
[void]$L.Add("          $hex = $code.ToString('x4')")
[void]$L.Add("          [void]$sb.Append($hex)")
[void]$L.Add("          continue")
[void]$L.Add("        }")
[void]$L.Add("        [void]$sb.Append([char]$code)")
[void]$L.Add("      }")
[void]$L.Add("    }")
[void]$L.Add("  }")
[void]$L.Add("  return $sb.ToString()")
[void]$L.Add("}")
[void]$L.Add("")
[void]$L.Add("function PC-ToCanonJson($v){")
[void]$L.Add("  if($null -eq $v){ return ""null"" }")
[void]$L.Add("  if($v -is [string]){ return ('""' + (PC-EscapeJsonString $v) + '""') }")
[void]$L.Add("  if($v -is [bool]){ return ($(if($v){'true'}else{'false'})) }")
[void]$L.Add("  if($v -is [int] -or $v -is [long] -or $v -is [double] -or $v -is [decimal]){ return ([string]::Format([System.Globalization.CultureInfo]::InvariantCulture,'{0}',$v)) }")
[void]$L.Add("  if($v -is [hashtable] -or $v -is [System.Collections.IDictionary]){")
[void]$L.Add("    $keys = @(@($v.Keys) | ForEach-Object { [string]$_ } | Sort-Object)")
[void]$L.Add("    $parts = New-Object System.Collections.Generic.List[string]")
[void]$L.Add("    foreach($kk in @($keys)){")
[void]$L.Add("      $k = [string]$kk")
[void]$L.Add("      $vv = $v[$k]")
[void]$L.Add("      [void]$parts.Add(('""' + (PC-EscapeJsonString $k) + '"":' + (PC-ToCanonJson $vv)))")
[void]$L.Add("    }")
[void]$L.Add("    return ('{' + (@($parts) -join ',') + '}')")
[void]$L.Add("  }")
[void]$L.Add("  if($v -is [System.Collections.IEnumerable] -and -not ($v -is [string])){")
[void]$L.Add("    $parts = New-Object System.Collections.Generic.List[string]")
[void]$L.Add("    foreach($it in @($v)){ [void]$parts.Add((PC-ToCanonJson $it)) }")
[void]$L.Add("    return ('[' + (@($parts) -join ',') + ']')")
[void]$L.Add("  }")
[void]$L.Add("  return ('""' + (PC-EscapeJsonString ([string]$v)) + '""')")
[void]$L.Add("}")
[void]$L.Add("")
[void]$L.Add("function PC-CanonBytesFromCanonJson([string]$canon){ $t=($canon -replace ""`r`n"",""`n"") -replace ""`r"",""`n""; if(-not $t.EndsWith(""`n"")){ $t += ""`n"" }; $enc=New-Object System.Text.UTF8Encoding($false); return $enc.GetBytes($t) }")
[void]$L.Add("function PC-ComputePacketIdFromManifestNoIdCanon([string]$manifestCanonNoId){ return (PC-Sha256HexBytes (PC-CanonBytesFromCanonJson $manifestCanonNoId)) }")
[void]$L.Add("function PC-RelPath([string]$Root,[string]$Full){ $r=[System.IO.Path]::GetFullPath($Root); $f=[System.IO.Path]::GetFullPath($Full); if(-not $f.StartsWith($r,[System.StringComparison]::OrdinalIgnoreCase)){ PC-Die (""PC-RelPath: not under root: "" + $Full) }; $rel=$f.Substring($r.Length).TrimStart('\','/'); return ($rel -replace '\','/') }")
[void]$L.Add("function PC-ListFilesRec([string]$Dir){ if(-not (Test-Path -LiteralPath $Dir -PathType Container)){ PC-Die (""MISSING_DIR: "" + $Dir) }; return @(@(Get-ChildItem -LiteralPath $Dir -Recurse -File -Force | Sort-Object FullName)) }")
WriteUtf8NoBomLf $libPath ((@($L) -join "`n") + "`n")
ParseGateFile $libPath

$builderPath = Join-Path $ScriptsDir "pc_build_packet_optionA_v1.ps1"
$B = New-Object System.Collections.Generic.List[string]
[void]$B.Add("param([Parameter(Mandatory=$true)][string]$RepoRoot,[Parameter(Mandatory=$true)][string]$PayloadDir,[Parameter(Mandatory=$true)][string]$OutDir,[Parameter(Mandatory=$false)][string]$PacketName = ""packet"")")
[void]$B.Add("Set-StrictMode -Version Latest")
[void]$B.Add("$ErrorActionPreference = ""Stop""")
[void]$B.Add(". (Join-Path $PSScriptRoot ""_lib_packet_constitution_v1.ps1"")")
[void]$B.Add("if(-not (Test-Path -LiteralPath $PayloadDir -PathType Container)){ PC-Die (""MISSING_PAYLOAD_DIR: "" + $PayloadDir) }")
[void]$B.Add("PC-EnsureDir $OutDir")
[void]$B.Add("$work = Join-Path $OutDir ($PacketName + ""_work"")")
[void]$B.Add("if(Test-Path -LiteralPath $work){ Remove-Item -LiteralPath $work -Recurse -Force }")
[void]$B.Add("PC-EnsureDir $work")
[void]$B.Add("$pktPayload = Join-Path $work ""payload""; PC-EnsureDir $pktPayload")
[void]$B.Add("Copy-Item -LiteralPath (Join-Path $PayloadDir ""*"") -Destination $pktPayload -Recurse -Force")
[void]$B.Add("$files = New-Object System.Collections.Generic.List[object]")
[void]$B.Add("$all = PC-ListFilesRec $work")
[void]$B.Add("foreach($f in @($all)){ $rel=PC-RelPath $work $f.FullName; if($rel -ieq ""manifest.json"" -or $rel -ieq ""packet_id.txt"" -or $rel -ieq ""sha256sums.txt""){ continue }; $h=PC-Sha256HexFile $f.FullName; $o=@{}; $o['path']=$rel; $o['bytes']=[int64]$f.Length; $o['sha256']=$h; [void]$files.Add($o) }")
[void]$B.Add("$m=@{}; $m['schema']='packet.manifest.v1'; $m['option']='A'; $m['created_utc']=PC-NowUtc; $m['files']=@($files)")
[void]$B.Add("$manifestCanonNoId = PC-ToCanonJson $m")
[void]$B.Add("$manifestPath = Join-Path $work ""manifest.json""; PC-WriteUtf8NoBomLf $manifestPath $manifestCanonNoId")
[void]$B.Add("PC-EnsureDir (Join-Path $work ""signatures"")")
[void]$B.Add("$packetId = PC-ComputePacketIdFromManifestNoIdCanon $manifestCanonNoId")
[void]$B.Add("$pidPath = Join-Path $work ""packet_id.txt""; PC-WriteUtf8NoBomLf $pidPath ($packetId + ""`n"")")
[void]$B.Add("$all2 = PC-ListFilesRec $work; $lines=New-Object System.Collections.Generic.List[string]")
[void]$B.Add("foreach($f in @($all2)){ $rel=PC-RelPath $work $f.FullName; if($rel -ieq ""sha256sums.txt""){ continue }; $h=PC-Sha256HexFile $f.FullName; [void]$lines.Add((""{0}  {1}"" -f $h,$rel)) }")
[void]$B.Add("$sumPath = Join-Path $work ""sha256sums.txt""; PC-WriteUtf8NoBomLf $sumPath ((@($lines) -join ""`n"") + ""`n"")")
[void]$B.Add("$final = Join-Path $OutDir $packetId; if(Test-Path -LiteralPath $final){ Remove-Item -LiteralPath $final -Recurse -Force }")
[void]$B.Add("Move-Item -LiteralPath $work -Destination $final")
[void]$B.Add("Write-Output $final")
WriteUtf8NoBomLf $builderPath ((@($B) -join "`n") + "`n")
ParseGateFile $builderPath

$verPath = Join-Path $ScriptsDir "pc_verify_packet_optionA_v1.ps1"
$V = New-Object System.Collections.Generic.List[string]
[void]$V.Add("param([Parameter(Mandatory=$true)][string]$PacketDir)")
[void]$V.Add("Set-StrictMode -Version Latest")
[void]$V.Add("$ErrorActionPreference = ""Stop""")
[void]$V.Add(". (Join-Path $PSScriptRoot ""_lib_packet_constitution_v1.ps1"")")
[void]$V.Add("if(-not (Test-Path -LiteralPath $PacketDir -PathType Container)){ PC-Die (""MISSING_PACKET_DIR: "" + $PacketDir) }")
[void]$V.Add("$packetDirName = Split-Path -Leaf $PacketDir")
[void]$V.Add("$manifestPath = Join-Path $PacketDir ""manifest.json""; $pidPath = Join-Path $PacketDir ""packet_id.txt""; $sumPath = Join-Path $PacketDir ""sha256sums.txt""")
[void]$V.Add("foreach($p in @($manifestPath,$pidPath,$sumPath)){ if(-not (Test-Path -LiteralPath $p -PathType Leaf)){ PC-Die (""MISSING_REQUIRED_FILE: "" + $p) } }")
[void]$V.Add("$raw = Get-Content -Raw -LiteralPath $sumPath -Encoding UTF8")
[void]$V.Add("$lines = @(@($raw -split ""`n"") | Where-Object { $_ -and $_.Trim().Length -gt 0 })")
[void]$V.Add("foreach($ln in @($lines)){ $m=[regex]::Match($ln,'^(?<h>[0-9a-f]{64})\s\s(?<p>.+)$'); if(-not $m.Success){ PC-Die ('BAD_SHA256SUMS_LINE: ' + $ln) }; $h=$m.Groups['h'].Value; $rel=$m.Groups['p'].Value; $full=Join-Path $PacketDir ($rel -replace '/','\ '); $full=$full -replace '\ ','\';
  if(-not (Test-Path -LiteralPath $full -PathType Leaf)){ PC-Die ('MISSING_FILE_LISTED_IN_SHA256SUMS: ' + $rel) }; $hh=PC-Sha256HexFile $full; if($hh -ne $h){ PC-Die ('SHA256_MISMATCH: ' + $rel + ' expected=' + $h + ' got=' + $hh) } }")
[void]$V.Add("$pid = (Get-Content -Raw -LiteralPath $pidPath -Encoding UTF8).Trim()")
[void]$V.Add("$manifestRaw = Get-Content -Raw -LiteralPath $manifestPath -Encoding UTF8")
[void]$V.Add("$manifestCanon = ($manifestRaw -replace ""`r`n"",""`n"") -replace ""`r"",""`n""")
[void]$V.Add("$expected = PC-ComputePacketIdFromManifestNoIdCanon $manifestCanon")
[void]$V.Add("if($expected -ne $pid){ PC-Die (""PACKET_ID_MISMATCH: expected="" + $expected + "" file="" + $pid) }")
[void]$V.Add("if($packetDirName -ne $pid){ PC-Die (""PACKET_DIRNAME_MISMATCH: dir="" + $packetDirName + "" pid="" + $pid) }")
[void]$V.Add("Write-Host (""VERIFY_OK: "" + $PacketDir) -ForegroundColor Green")
WriteUtf8NoBomLf $verPath ((@($V) -join "`n") + "`n")
ParseGateFile $verPath

$selfPath = Join-Path $ScriptsDir "_selftest_packet_constitution_v1.ps1"
$S = New-Object System.Collections.Generic.List[string]
[void]$S.Add("param([Parameter(Mandatory=$true)][string]$RepoRoot)")
[void]$S.Add("Set-StrictMode -Version Latest")
[void]$S.Add("$ErrorActionPreference = ""Stop""")
[void]$S.Add(". (Join-Path $PSScriptRoot ""_lib_packet_constitution_v1.ps1"")")
[void]$S.Add("$tv = Join-Path $RepoRoot ""test_vectors\packet_constitution_v1\v1_minimal_optionA""")
[void]$S.Add("$payload = Join-Path $tv ""payload""; $out = Join-Path $tv ""out""; $gold = Join-Path $tv ""golden""")
[void]$S.Add("PC-EnsureDir $tv; PC-EnsureDir $payload; PC-EnsureDir $out; PC-EnsureDir $gold")
[void]$S.Add("PC-WriteUtf8NoBomLf (Join-Path $payload ""hello.txt"") (""hello`n"")")
[void]$S.Add("$metaCanon = PC-ToCanonJson (@{ schema=""recognition.payload.meta.v1""; note=""minimal""; n=1 })")
[void]$S.Add("PC-WriteUtf8NoBomLf (Join-Path $payload ""meta.json"") $metaCanon")
[void]$S.Add("$builder = Join-Path $RepoRoot ""scripts\pc_build_packet_optionA_v1.ps1""")
[void]$S.Add("$ver = Join-Path $RepoRoot ""scripts\pc_verify_packet_optionA_v1.ps1""")
[void]$S.Add("$ps = Join-Path $env:WINDIR ""System32\WindowsPowerShell\v1.0\powershell.exe""")
[void]$S.Add("$pktDir = & $ps -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $builder -RepoRoot $RepoRoot -PayloadDir $payload -OutDir $out -PacketName ""tv""")
[void]$S.Add("if(-not (Test-Path -LiteralPath $pktDir -PathType Container)){ PC-Die (""SELFTEST_BUILD_FAIL: "" + $pktDir) }")
[void]$S.Add("& $ps -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $ver -PacketDir $pktDir | Out-Host")
[void]$S.Add("Copy-Item -LiteralPath (Join-Path $pktDir ""manifest.json"") -Destination (Join-Path $gold ""manifest_without_id.canon.json"") -Force")
[void]$S.Add("Copy-Item -LiteralPath (Join-Path $pktDir ""packet_id.txt"") -Destination (Join-Path $gold ""packet_id.txt"") -Force")
[void]$S.Add("Copy-Item -LiteralPath (Join-Path $pktDir ""sha256sums.txt"") -Destination (Join-Path $gold ""sha256sums.txt"") -Force")
[void]$S.Add("$gm = Get-Content -Raw -LiteralPath (Join-Path $gold ""manifest_without_id.canon.json"") -Encoding UTF8")
[void]$S.Add("$gp = (Get-Content -Raw -LiteralPath (Join-Path $gold ""packet_id.txt"") -Encoding UTF8).Trim()")
[void]$S.Add("$ep = PC-ComputePacketIdFromManifestNoIdCanon $gm")
[void]$S.Add("if($ep -ne $gp){ PC-Die (""GOLDEN_PACKET_ID_MISMATCH: expected="" + $ep + "" golden="" + $gp) }")
[void]$S.Add("Write-Host (""SELFTEST_OK: Packet Constitution v1 Option A minimal vector -> "" + $tv) -ForegroundColor Green")
WriteUtf8NoBomLf $selfPath ((@($S) -join "`n") + "`n")
ParseGateFile $selfPath

$expPath = Join-Path $ScriptsDir "recognition_export_session_packet_v1.ps1"
$E = New-Object System.Collections.Generic.List[string]
[void]$E.Add("param([Parameter(Mandatory=$true)][string]$RepoRoot,[Parameter(Mandatory=$false)][string]$SessionExportDir,[Parameter(Mandatory=$false)][string]$OutDir,[Parameter(Mandatory=$false)][string]$PacketName = ""recognition_session_export"")")
[void]$E.Add("Set-StrictMode -Version Latest")
[void]$E.Add("$ErrorActionPreference = ""Stop""")
[void]$E.Add(". (Join-Path $PSScriptRoot ""_lib_packet_constitution_v1.ps1"")")
[void]$E.Add("if([string]::IsNullOrWhiteSpace($SessionExportDir)){ $SessionExportDir = Join-Path $RepoRoot ""payload\session_export"" }")
[void]$E.Add("if([string]::IsNullOrWhiteSpace($OutDir)){ $OutDir = Join-Path $RepoRoot ""packets\outbox"" }")
[void]$E.Add("if(-not (Test-Path -LiteralPath $SessionExportDir -PathType Container)){ PC-Die (""MISSING_SESSION_EXPORT_DIR: "" + $SessionExportDir) }")
[void]$E.Add("PC-EnsureDir $OutDir")
[void]$E.Add("$builder = Join-Path $RepoRoot ""scripts\pc_build_packet_optionA_v1.ps1""")
[void]$E.Add("if(-not (Test-Path -LiteralPath $builder -PathType Leaf)){ PC-Die (""MISSING_BUILDER: "" + $builder) }")
[void]$E.Add("$ps = Join-Path $env:WINDIR ""System32\WindowsPowerShell\v1.0\powershell.exe""")
[void]$E.Add("$pktDir = & $ps -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $builder -RepoRoot $RepoRoot -PayloadDir $SessionExportDir -OutDir $OutDir -PacketName $PacketName")
[void]$E.Add("if(-not (Test-Path -LiteralPath $pktDir -PathType Container)){ PC-Die (""EXPORT_BUILD_FAIL: "" + $pktDir) }")
[void]$E.Add("Write-Host (""EXPORT_OK: "" + $pktDir) -ForegroundColor Green")
[void]$E.Add("Write-Output $pktDir")
WriteUtf8NoBomLf $expPath ((@($E) -join "`n") + "`n")
ParseGateFile $expPath

& (Join-Path $env:WINDIR "System32\WindowsPowerShell\v1.0\powershell.exe") -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $selfPath -RepoRoot $RepoRoot | Out-Host
Write-Host ("PATCH_OK: Packet Constitution v1 Option A installed + selftested; exporter ready -> " + $expPath) -ForegroundColor Green
