Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function RR-Die([string]$m){ throw ("RR_FAIL: " + $m) }
function RR-EnsureDir([string]$p){ if([string]::IsNullOrWhiteSpace($p)){ RR-Die "ENSUREDIR_EMPTY" }; if(-not (Test-Path -LiteralPath $p -PathType Container)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function RR-WriteUtf8NoBomLf([string]$Path,[string]$Text){ $enc = New-Object System.Text.UTF8Encoding($false); $lf = ($Text -replace "`r`n","`n") -replace "`r","`n"; if(-not $lf.EndsWith("`n")){ $lf += "`n" }; $dir = Split-Path -Parent $Path; if($dir){ RR-EnsureDir $dir }; [System.IO.File]::WriteAllText($Path,$lf,$enc) }
function RR-ReadUtf8([string]$Path){ if(-not (Test-Path -LiteralPath $Path -PathType Leaf)){ RR-Die ("MISSING_FILE: " + $Path) }; Get-Content -Raw -LiteralPath $Path -Encoding UTF8 }
function RR-CanonJson([object]$obj){ $pc = Join-Path $PSScriptRoot "_lib_packet_constitution_v1.ps1"; if(-not (Test-Path -LiteralPath $pc -PathType Leaf)){ RR-Die ("MISSING_PC_LIB: " + $pc) }; . $pc; PC-ToCanonJson $obj }
function RR-RuntimeRoot([string]$RepoRoot){ Join-Path $RepoRoot "runtime" }
function RR-SessionDir([string]$RepoRoot){ Join-Path (RR-RuntimeRoot $RepoRoot) "session" }
function RR-TabsDir([string]$RepoRoot){ Join-Path (RR-RuntimeRoot $RepoRoot) "tabs" }
function RR-EventsPath([string]$RepoRoot){ Join-Path (RR-RuntimeRoot $RepoRoot) "events.ndjson" }
function RR-SessionStatePath([string]$RepoRoot){ Join-Path (RR-SessionDir $RepoRoot) "session_state.json" }
function RR-TabStatePath([string]$RepoRoot,[string]$TabId){ Join-Path (RR-TabsDir $RepoRoot) ($TabId + ".json") }
function RR-EnsureRuntimeLayout([string]$RepoRoot){ RR-EnsureDir (RR-RuntimeRoot $RepoRoot); RR-EnsureDir (RR-SessionDir $RepoRoot); RR-EnsureDir (RR-TabsDir $RepoRoot); $eventsPath = RR-EventsPath $RepoRoot; if(-not (Test-Path -LiteralPath $eventsPath -PathType Leaf)){ RR-WriteUtf8NoBomLf $eventsPath "" } }
function RR-ReadJsonObject([string]$Path){ $raw = RR-ReadUtf8 $Path; if([string]::IsNullOrWhiteSpace($raw)){ return $null }; $raw | ConvertFrom-Json }
function RR-ReadSessionState([string]$RepoRoot){ $p = RR-SessionStatePath $RepoRoot; if(-not (Test-Path -LiteralPath $p -PathType Leaf)){ return $null }; RR-ReadJsonObject $p }
function RR-WriteSessionState([string]$RepoRoot,[hashtable]$State){ RR-EnsureRuntimeLayout $RepoRoot; RR-WriteUtf8NoBomLf (RR-SessionStatePath $RepoRoot) (RR-CanonJson $State) }
function RR-ReadTabState([string]$RepoRoot,[string]$TabId){ $p = RR-TabStatePath $RepoRoot $TabId; if(-not (Test-Path -LiteralPath $p -PathType Leaf)){ return $null }; RR-ReadJsonObject $p }
function RR-WriteTabState([string]$RepoRoot,[string]$TabId,[hashtable]$State){ RR-EnsureRuntimeLayout $RepoRoot; RR-WriteUtf8NoBomLf (RR-TabStatePath $RepoRoot $TabId) (RR-CanonJson $State) }
function RR-GetNextSeq([string]$RepoRoot){ RR-EnsureRuntimeLayout $RepoRoot; $raw = RR-ReadUtf8 (RR-EventsPath $RepoRoot); if([string]::IsNullOrWhiteSpace($raw)){ return 1 }; $lines = @(@($raw -split "`n") | Where-Object { $_ -and $_.Trim().Length -gt 0 }); if($lines.Count -eq 0){ return 1 }; $last = $lines[-1] | ConvertFrom-Json; return ([int]$last.seq + 1) }
function RR-AppendEvent([string]$RepoRoot,[hashtable]$Event){ RR-EnsureRuntimeLayout $RepoRoot; $canon = RR-CanonJson $Event; $path = RR-EventsPath $RepoRoot; $enc = New-Object System.Text.UTF8Encoding($false); $text = ($canon -replace "`r`n","`n") -replace "`r","`n"; if(-not $text.EndsWith("`n")){ $text += "`n" }; [System.IO.File]::AppendAllText($path,$text,$enc) }
function RR-ExportRuntimeToSessionPayload([string]$RepoRoot,[string]$OutDir){ RR-EnsureRuntimeLayout $RepoRoot; RR-EnsureDir $OutDir; $session = RR-ReadSessionState $RepoRoot; if($null -eq $session){ RR-Die "SESSION_STATE_MISSING" }; $tabFiles = @(@(Get-ChildItem -LiteralPath (RR-TabsDir $RepoRoot) -File -Force | Sort-Object FullName)); $tabs = New-Object System.Collections.Generic.List[object]; foreach($f in $tabFiles){ $raw = RR-ReadUtf8 $f.FullName; if([string]::IsNullOrWhiteSpace($raw)){ continue }; [void]$tabs.Add(($raw | ConvertFrom-Json)) }; $sessionObj = @{ schema="recognition.session.v1"; session_id=[string]$session.session_id; started_utc=[string]$session.started_utc; ended_utc=$session.ended_utc; mode=[string]$session.mode; runtime=@{ platform=[string]$session.platform; surface=[string]$session.surface; recognition_version=[string]$session.recognition_version } }; $tabsObj = @{ schema="recognition.tabs.v1"; tabs=@($tabs) }; $policyObj = @{ schema="recognition.policy_state.v1"; policy_pack_id="recognition.standard.v1"; policy_pack_version=1; mode=[string]$session.mode; effective_rules=@(); default_network_policy="allow"; default_storage_policy="allow" }; $trustObj = @{ schema="recognition.trust_context.v1"; trust_bundle_present=(Test-Path -LiteralPath (Join-Path $RepoRoot "proofs\trust\trust_bundle.json") -PathType Leaf); trust_bundle_path="proofs/trust/trust_bundle.json"; allowed_signers_path="proofs/trust/allowed_signers"; active_principal=$null }; $vpnObj = @{ schema="recognition.vpn_state.v1"; vpn_mode="off"; vpn_connected=$false; kill_switch_enabled=$false; provider_id=$null }; $exportManifestObj = @{ schema="recognition.session_export_manifest.v1"; session_schema="recognition.session.v1"; tabs_schema="recognition.tabs.v1"; events_schema="recognition.event.v1"; policy_state_schema="recognition.policy_state.v1"; trust_context_schema="recognition.trust_context.v1"; vpn_state_schema="recognition.vpn_state.v1" }; RR-WriteUtf8NoBomLf (Join-Path $OutDir "session.json") (RR-CanonJson $sessionObj); RR-WriteUtf8NoBomLf (Join-Path $OutDir "tabs.json") (RR-CanonJson $tabsObj); RR-WriteUtf8NoBomLf (Join-Path $OutDir "policy_state.json") (RR-CanonJson $policyObj); RR-WriteUtf8NoBomLf (Join-Path $OutDir "trust_context.json") (RR-CanonJson $trustObj); RR-WriteUtf8NoBomLf (Join-Path $OutDir "vpn_state.json") (RR-CanonJson $vpnObj); RR-WriteUtf8NoBomLf (Join-Path $OutDir "export_manifest.json") (RR-CanonJson $exportManifestObj); $eventsRaw = RR-ReadUtf8 (RR-EventsPath $RepoRoot); RR-WriteUtf8NoBomLf (Join-Path $OutDir "events.ndjson") $eventsRaw }
