Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
param([Parameter(Mandatory=$true)][string]$RepoRoot)

function Die([string]$m){ throw $m }
function EnsureDir([string]$p){ if([string]::IsNullOrWhiteSpace($p)){ Die "EnsureDir: empty path" }; if(-not (Test-Path -LiteralPath $p -PathType Container)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function WriteUtf8NoBomLf([string]$Path,[string]$Text){ $enc=New-Object System.Text.UTF8Encoding($false); $lf=($Text -replace "`r`n","`n") -replace "`r","`n"; if(-not $lf.EndsWith("`n")){ $lf += "`n" }; EnsureDir (Split-Path -Parent $Path); [System.IO.File]::WriteAllText($Path,$lf,$enc) }
function ParseGateFile([string]$Path){ $raw = Get-Content -Raw -LiteralPath $Path -Encoding UTF8; $null = [ScriptBlock]::Create($raw) }

$ScriptsDir = Join-Path $RepoRoot "scripts"
$Target = Join-Path $ScriptsDir "recognition_bootstrap_v1.ps1"
EnsureDir $ScriptsDir

# Rewrite bootstrap script entirely (ASCII-only, PS5.1 parse-safe)
$L = New-Object System.Collections.Generic.List[string]
[void]$L.Add("Set-StrictMode -Version Latest")
[void]$L.Add("$ErrorActionPreference = ""Stop""")
[void]$L.Add("")
[void]$L.Add("function Die([string]$m){ throw $m }")
[void]$L.Add("function NowUtc(){ (Get-Date).ToUniversalTime().ToString(""yyyy-MM-ddTHH:mm:ss.fffZ"") }")
[void]$L.Add("function EnsureDir([string]$p){ if([string]::IsNullOrWhiteSpace($p)){ Die ""EnsureDir: empty path"" }; if(-not (Test-Path -LiteralPath $p -PathType Container)){ New-Item -ItemType Directory -Force -Path $p | Out-Null } }")
[void]$L.Add("function WriteUtf8NoBomLf([string]$Path,[string]$Text){ $enc=New-Object System.Text.UTF8Encoding($false); $lf=($Text -replace ""`r`n"",""`n"") -replace ""`r"",""`n""; if(-not $lf.EndsWith(""`n"")){ $lf += ""`n"" }; EnsureDir (Split-Path -Parent $Path); [System.IO.File]::WriteAllText($Path,$lf,$enc) }")
[void]$L.Add("function ParseGateFile([string]$Path){ if(-not (Test-Path -LiteralPath $Path -PathType Leaf)){ Die (""PARSE_GATE_MISSING: "" + $Path) }; $raw = Get-Content -Raw -LiteralPath $Path -Encoding UTF8; $null = [ScriptBlock]::Create($raw) }")
[void]$L.Add("")
[void]$L.Add("param([Parameter(Mandatory=$true)][string]$RepoRoot)")
[void]$L.Add("")
[void]$L.Add("$dirs = @('docs','schemas','policy/canonical','policy/overlay','proofs/keys','proofs/trust','proofs/receipts','packets/outbox','packets/inbox','packets/quarantine','packets/receipts','scripts','src','test_vectors/packet_constitution_v1','test_vectors/recognition_policy_v1')")
[void]$L.Add("foreach($d in @($dirs)){ EnsureDir (Join-Path $RepoRoot $d) }")
[void]$L.Add("")
[void]$L.Add("function WriteLines([string]$Rel,[string[]]$Lines){ $p = Join-Path $RepoRoot $Rel; $txt = (@($Lines) -join ""`n"") + ""`n""; WriteUtf8NoBomLf $p $txt }")
[void]$L.Add("")
[void]$L.Add("WriteLines ""README.md"" @(")
[void]$L.Add("  ""# Recognition""," )
[void]$L.Add("  """"," )
[void]$L.Add("  ""Recognition is a lightweight Windows-first browser (WebView2) that is strong like Opera, safe like Brave, and protected like DuckDuckGo - but governed and exportable under the ecosystem laws.""," )
[void]$L.Add("  """"," )
[void]$L.Add("  ""## Canonical Laws""," )
[void]$L.Add("  ""- NFL duplication is non-optional for defined events (install/update/policy/trust/vpn/session export).""," )
[void]$L.Add("  ""- NeverLost v1 identity + deterministic receipts.""," )
[void]$L.Add("  ""- Packet Constitution v1 for exportable directory-bundle packets.""," )
[void]$L.Add("  ""- WatchTower verification compatible; Covenant Gate policy gating later.""," )
[void]$L.Add("  """"," )
[void]$L.Add("  ""## Repo Layout""," )
[void]$L.Add("  ""- `schemas/`: canonical event schemas""," )
[void]$L.Add("  ""- `policy/`: policy packs (canonical + overlay)""," )
[void]$L.Add("  ""- `proofs/`: trust bundles + receipts""," )
[void]$L.Add("  ""- `packets/`: outbox/inbox/quarantine + receipts""," )
[void]$L.Add("  ""- `scripts/`: deterministic tooling (bootstrap/export/dup/selftests)""")
[void]$L.Add(")")
[void]$L.Add("")
[void]$L.Add("WriteLines ""SPEC_Recognition_v1.md"" @(")
[void]$L.Add("  ""# Recognition v1 Specification (Canonical)""," )
[void]$L.Add("  """"," )
[void]$L.Add("  ""## Non-negotiables""," )
[void]$L.Add("  ""- NFL duplication is mandatory for: install, update, policy pack set, trust bundle set, vpn plan/state, session export.""," )
[void]$L.Add("  ""- Standalone privacy + VPN. AnchorMark integration is optional (never required).""," )
[void]$L.Add("  ""- Export discipline: Packet Constitution v1 session packets.""," )
[void]$L.Add("  """"," )
[void]$L.Add("  ""## Modes""," )
[void]$L.Add("  ""- Standard / Strict / Private / Private+VPN / Airgap""," )
[void]$L.Add("  ""- Private: no history persistence; session containers wiped on exit.""," )
[void]$L.Add("  ""- Strict: deny-by-default capabilities + aggressive protection.""," )
[void]$L.Add("  ""- Airgap: networking disabled at gate; local files/packets allowed.""," )
[void]$L.Add("  """"," )
[void]$L.Add("  ""## Policy packs""," )
[void]$L.Add("  ""Policy packs are hash-addressed JSON describing defaults + site rules + capability gating.""," )
[void]$L.Add("  """"," )
[void]$L.Add("  ""## VPN tiers""," )
[void]$L.Add("  ""- Free: limited data allocation, manual connect.""," )
[void]$L.Add("  ""- Premium: always-on/constant VPN + kill-switch + higher allocation.""," )
[void]$L.Add("  """"," )
[void]$L.Add("  ""## Evidence + export""," )
[void]$L.Add("  ""- Session export emits a Packet Constitution v1 directory-bundle packet containing transcript, decisions, relevant policy/trust, and receipts.""," )
[void]$L.Add("  ""- Export event is duplicated to NFL (non-optional).""")
[void]$L.Add(")")
[void]$L.Add("")
[void]$L.Add("WriteLines ""docs/threat_model_v1.md"" @(""# Threat Model v1"","""",""Placeholder: attacker goals + trust boundaries + mitigations."")")
[void]$L.Add("WriteLines ""docs/vpn_tiers_v1.md"" @(""# VPN Tiers v1"","""",""Free: capped allocation. Premium: always-on + kill-switch + higher allocation. Target: WireGuard behind Recognition.VpnCore."")")
[void]$L.Add("WriteLines ""docs/decisions_and_receipts_v1.md"" @(""# Decisions & Receipts v1"","""",""Deterministic decision records + receipts; NFL duplication mandatory for canonical events."")")
[void]$L.Add("WriteLines ""docs/update_and_release_v1.md"" @(""# Update & Release v1"","""",""Placeholder: signed installers, update receipts, mandatory NFL duplication on install/update."")")
[void]$L.Add("")
[void]$L.Add("WriteLines ""policy/canonical/policy_pack_recognition_standard_v1.json"" @(")
[void]$L.Add("  ""{""," )
[void]$L.Add("  ""  \""schema\"": \""recognition.policy_pack.v1\"", ""," )
[void]$L.Add("  ""  \""pack_id\"": \""recognition.standard.v1\"", ""," )
[void]$L.Add("  ""  \""pack_version\"": 1,""," )
[void]$L.Add("  ""  \""defaults\"": {""," )
[void]$L.Add("  ""    \""protection\"": { \""tracker_blocking\"": true, \""https_first\"": true, \""fingerprinting_resistance_level\"": \""basic\"" },""," )
[void]$L.Add("  ""    \""capabilities\"": { \""js\"": \""allow\"", \""cookies\"": \""allow\"", \""storage\"": \""allow\"", \""camera\"": \""ask\"", \""mic\"": \""ask\"", \""location\"": \""ask\"", \""clipboard\"": \""ask\"", \""popups\"": \""deny\"", \""downloads\"": \""allow\"", \""external_open\"": \""ask\"" }""," )
[void]$L.Add("  ""  },""," )
[void]$L.Add("  ""  \""rules\"": []""," )
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("WriteLines ""policy/canonical/policy_pack_recognition_strict_v1.json"" @(")
[void]$L.Add("  ""{""," )
[void]$L.Add("  ""  \""schema\"": \""recognition.policy_pack.v1\"", ""," )
[void]$L.Add("  ""  \""pack_id\"": \""recognition.strict.v1\"", ""," )
[void]$L.Add("  ""  \""pack_version\"": 1,""," )
[void]$L.Add("  ""  \""defaults\"": {""," )
[void]$L.Add("  ""    \""protection\"": { \""tracker_blocking\"": true, \""https_first\"": true, \""fingerprinting_resistance_level\"": \""strong\"" },""," )
[void]$L.Add("  ""    \""capabilities\"": { \""js\"": \""ask\"", \""cookies\"": \""deny\"", \""storage\"": \""deny\"", \""camera\"": \""deny\"", \""mic\"": \""deny\"", \""location\"": \""deny\"", \""clipboard\"": \""deny\"", \""popups\"": \""deny\"", \""downloads\"": \""ask\"", \""external_open\"": \""deny\"" }""," )
[void]$L.Add("  ""  },""," )
[void]$L.Add("  ""  \""rules\"": []""," )
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("WriteLines ""policy/canonical/policy_pack_recognition_private_v1.json"" @(")
[void]$L.Add("  ""{""," )
[void]$L.Add("  ""  \""schema\"": \""recognition.policy_pack.v1\"", ""," )
[void]$L.Add("  ""  \""pack_id\"": \""recognition.private.v1\"", ""," )
[void]$L.Add("  ""  \""pack_version\"": 1,""," )
[void]$L.Add("  ""  \""defaults\"": {""," )
[void]$L.Add("  ""    \""protection\"": { \""tracker_blocking\"": true, \""https_first\"": true, \""fingerprinting_resistance_level\"": \""basic\"" },""," )
[void]$L.Add("  ""    \""capabilities\"": { \""js\"": \""allow\"", \""cookies\"": \""session_only\"", \""storage\"": \""session_only\"", \""camera\"": \""deny\"", \""mic\"": \""deny\"", \""location\"": \""deny\"", \""clipboard\"": \""ask\"", \""popups\"": \""deny\"", \""downloads\"": \""ask\"", \""external_open\"": \""deny\"" }""," )
[void]$L.Add("  ""  },""," )
[void]$L.Add("  ""  \""rules\"": []""," )
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("WriteLines ""policy/overlay/README.md"" @(""# Overlay policy packs"","""",""Put local overrides here. Overlay is layered on top of canonical policy."")")
[void]$L.Add("")
[void]$L.Add("WriteLines ""proofs/trust/trust_bundle.json"" @(")
[void]$L.Add("  ""{""," )
[void]$L.Add("  ""  \""schema\"": \""neverlost.trust_bundle.v1\"", ""," )
[void]$L.Add("  ""  \""note\"": \""Bootstrap placeholder. Replace with real trust bundle and derive allowed_signers deterministically.\"""," )
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("WriteLines ""proofs/trust/allowed_signers"" @(""# allowed_signers (placeholder)"","""",""# Derive from trust_bundle.json via scripts/make_allowed_signers_v1.ps1"")")
[void]$L.Add("WriteLines ""proofs/receipts/neverlost.ndjson"" @()")
[void]$L.Add("")
[void]$L.Add("WriteLines ""schemas/recognition.download_receipt.v1.json"" @(")
[void]$L.Add("  ""{""," )
[void]$L.Add("  ""  \""$schema\"": \""https://json-schema.org/draft/2020-12/schema\"", ""," )
[void]$L.Add("  ""  \""title\"": \""recognition.download_receipt.v1\"", ""," )
[void]$L.Add("  ""  \""type\"": \""object\"", ""," )
[void]$L.Add("  ""  \""required\"": [\""event\"",\""utc\"",\""download_id\"",\""url\"",\""sha256\"",\""bytes\"",\""sig_verification\"",\""stored_as\""],""," )
[void]$L.Add("  ""  \""properties\"": {""," )
[void]$L.Add("  ""    \""event\"": { \""const\"": \""recognition.download_receipt.v1\"" },""," )
[void]$L.Add("  ""    \""utc\"": { \""type\"": \""string\"" },""," )
[void]$L.Add("  ""    \""download_id\"": { \""type\"": \""string\"" },""," )
[void]$L.Add("  ""    \""url\"": { \""type\"": \""string\"" },""," )
[void]$L.Add("  ""    \""sha256\"": { \""type\"": \""string\"" },""," )
[void]$L.Add("  ""    \""content_type\"": { \""type\"": \""string\"" },""," )
[void]$L.Add("  ""    \""bytes\"": { \""type\"": \""integer\"" },""," )
[void]$L.Add("  ""    \""sig_verification\"": { \""enum\"": [\""not_present\"",\""ok\"",\""fail\""] },""," )
[void]$L.Add("  ""    \""stored_as\"": { \""enum\"": [\""pointer_only\"",\""local_path\"",\""sealed_blob\""] }""," )
[void]$L.Add("  ""  }""," )
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("")
[void]$L.Add("WriteLines ""schemas/recognition.policy_decision.v1.json"" @(")
[void]$L.Add("  ""{"" ,")
[void]$L.Add("  ""  \""title\"": \""recognition.policy_decision.v1\"", "" ,")
[void]$L.Add("  ""  \""type\"": \""object\""")
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("WriteLines ""schemas/recognition.session_transcript.v1.json"" @(")
[void]$L.Add("  ""{"" ,")
[void]$L.Add("  ""  \""title\"": \""recognition.session_transcript.v1\"", "" ,")
[void]$L.Add("  ""  \""type\"": \""object\""")
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("WriteLines ""schemas/recognition.nfl_event.v1.json"" @(")
[void]$L.Add("  ""{"" ,")
[void]$L.Add("  ""  \""title\"": \""recognition.nfl_event.v1\"", "" ,")
[void]$L.Add("  ""  \""type\"": \""object\""")
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("WriteLines ""schemas/recognition.vpn_state.v1.json"" @(")
[void]$L.Add("  ""{"" ,")
[void]$L.Add("  ""  \""title\"": \""recognition.vpn_state.v1\"", "" ,")
[void]$L.Add("  ""  \""type\"": \""object\""")
[void]$L.Add("  ""}""")
[void]$L.Add(")")
[void]$L.Add("")
[void]$L.Add("WriteUtf8NoBomLf (Join-Path $RepoRoot 'scripts/_lib_neverlost_v1.ps1') ('Set-StrictMode -Version Latest`n$ErrorActionPreference = ''Stop''`n')")
[void]$L.Add("")
WriteUtf8NoBomLf $Target ((@($L) -join "`n") + "`n")
ParseGateFile $Target
Write-Host ("PATCH_OK: rewrote bootstrap -> " + $Target) -ForegroundColor Green
